import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faArrowUp,
  faArrowDown,
  faExpand,
  faCompress,
  faBolt,
  faSpinner,
  faPowerOff,
  faBookBookmark,
  faBarsStaggered,
  faPlus,
  faInfo,
  faCheck,
  faWarning,
  faX,
  faExclamation,
} from '@fortawesome/free-solid-svg-icons'

import {
  faFacebookSquare,
  faTwitter,
  faLinkedin,
  faSkype,
  faGoogle,
  faInstagram,
  faYoutube,
  faFacebook,

} from '@fortawesome/free-brands-svg-icons'

library.add(
  faPlus,
  faInfo,
  faPowerOff,
  faBookBookmark,
  faBarsStaggered,
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faArrowUp,
  faArrowDown,
  faExpand,
  faCompress,
  faBolt,
  faSpinner,
  faFacebookSquare,
  faFacebook,
  faTwitter,
  faLinkedin,
  faSkype,
  faGoogle,
  faInstagram,
  faYoutube,
  faCheck,
  faWarning,
  faX,
  faExclamation,
)
